# Generated by Django 3.1.2 on 2021-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=100),
        ),
        migrations.AddField(
            model_name='newpost',
            name='location',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
